#!/bin/sh
# This script is called by the lambda execution environment when it
# receives the very first invocation request.

cd /var/task

# /usr/local/julia/bin/julia --project=. main.jl
/usr/local/julia/bin/julia -q -Jsysimage -e "include(\"main.jl\")"
