require "./simulation_runner.rb"

task default: %w[test]

task :compile do
  sim = SimulationRunner.new_from_json_export()
end

task :test_simple_seesaw do
  file = File.read("./modelica_model_generation/simple_seesaw.json")

  sim = SimulationRunner.new_from_json_export(file)
  p sim.get_period()
end

task :test_get_period do
  sim = SimulationRunner.new()
  p sim.get_period()
end

task default: %w[test]
